// Package config handles TAW configuration parsing and management.
package config

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/donghojung/taw/internal/constants"
)

// WorkMode defines how tasks work with git.
type WorkMode string

const (
	WorkModeWorktree WorkMode = "worktree" // Each task gets its own worktree
	WorkModeMain     WorkMode = "main"     // All tasks work on current branch
)

// OnComplete defines what happens when a task completes.
type OnComplete string

const (
	OnCompleteConfirm    OnComplete = "confirm"     // Ask before each action
	OnCompleteAutoCommit OnComplete = "auto-commit" // Auto commit, manual merge/PR
	OnCompleteAutoMerge  OnComplete = "auto-merge"  // Auto commit + merge + cleanup
	OnCompleteAutoPR     OnComplete = "auto-pr"     // Auto commit + create PR
)

// Config represents the TAW project configuration.
type Config struct {
	WorkMode   WorkMode   `yaml:"work_mode"`
	OnComplete OnComplete `yaml:"on_complete"`
}

// DefaultConfig returns the default configuration.
func DefaultConfig() *Config {
	return &Config{
		WorkMode:   WorkModeWorktree,
		OnComplete: OnCompleteConfirm,
	}
}

// Load reads the configuration from the given taw directory.
func Load(tawDir string) (*Config, error) {
	configPath := filepath.Join(tawDir, constants.ConfigFileName)

	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		return DefaultConfig(), nil
	}

	file, err := os.Open(configPath)
	if err != nil {
		return nil, fmt.Errorf("failed to open config: %w", err)
	}
	defer file.Close()

	cfg := DefaultConfig()
	scanner := bufio.NewScanner(file)

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		parts := strings.SplitN(line, ":", 2)
		if len(parts) != 2 {
			continue
		}

		key := strings.TrimSpace(parts[0])
		value := strings.TrimSpace(parts[1])

		switch key {
		case "work_mode":
			cfg.WorkMode = WorkMode(value)
		case "on_complete":
			cfg.OnComplete = OnComplete(value)
		}
	}

	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("failed to read config: %w", err)
	}

	return cfg, nil
}

// Save writes the configuration to the given taw directory.
func (c *Config) Save(tawDir string) error {
	configPath := filepath.Join(tawDir, constants.ConfigFileName)

	content := fmt.Sprintf(`# TAW Configuration
# Generated by taw setup

# Work mode: worktree or main
# - worktree: Each task gets its own git worktree (recommended)
# - main: All tasks work on the current branch
work_mode: %s

# On complete action: confirm, auto-commit, auto-merge, or auto-pr
# - confirm: Ask before each action (recommended)
# - auto-commit: Automatically commit changes
# - auto-merge: Auto commit + merge + cleanup + close window
# - auto-pr: Auto commit + create pull request
on_complete: %s
`, c.WorkMode, c.OnComplete)

	return os.WriteFile(configPath, []byte(content), 0644)
}

// Exists checks if a configuration file exists in the given taw directory.
func Exists(tawDir string) bool {
	configPath := filepath.Join(tawDir, constants.ConfigFileName)
	_, err := os.Stat(configPath)
	return err == nil
}

// ValidWorkModes returns all valid work modes.
func ValidWorkModes() []WorkMode {
	return []WorkMode{WorkModeWorktree, WorkModeMain}
}

// ValidOnCompletes returns all valid on_complete values.
func ValidOnCompletes() []OnComplete {
	return []OnComplete{
		OnCompleteConfirm,
		OnCompleteAutoCommit,
		OnCompleteAutoMerge,
		OnCompleteAutoPR,
	}
}
